FROM debian:stretch

RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y exim4

RUN rm -rf /etc/exim4 && mkdir -p /etc/exim4
ADD exim4.conf /etc/exim4/exim4.conf

ADD start.sh /exim
RUN chmod +x /exim

# VOLUME /var/spool/exim4
EXPOSE 25

ENTRYPOINT ["/exim"]