heartbeat.monitors:
- type: icmp
  schedule: '*/5 * * * * * *'
  hosts: ["filebeat","metricbeat","packetbeat","elasticsearch","logstash","kibana"]
  #ipv4: true
  #ipv6: true
  mode: any
  timeout: 16s
  wait: 1s

- type: http
  enabled: true
  schedule: '@every 5s'
  urls: ["http://elasticsearch:9200"]
  #ipv4: true
  #ipv6: true
  mode: any
  timeout: 5s
  # username: '${ES_USERNAME:elastic}'
  # password: '${ES_PASSWORD:changeme}'
  check.request:
    method: "GET"
  check.response:
    status: 200

- type: http
  enabled: true
  schedule: '@every 5s'
  urls: ["http://kibana:5601"]
  #ipv4: true
  #ipv6: true
  mode: any
  timeout: 5s
  check.request:
    method: "GET"
  check.response:
    status: 200

output.elasticsearch:
  hosts: ["localhost:9200"]
logging.to_files: false
setup.dashboards.enabled: true